validation:
  if_validate: false
  batch_size: 8
  save_model_every_n_epochs: 250
  check_val_every_n_epochs: 100
  check_val_monitor: val_loss/absolute_rssd
  save_top_k_models: 40
  early_stopping: true
  early_stopping_patience: 100
test:
  save_dir: /mlbio_scratch/anagupta/luna/LUNA/exp/test_results
  checkpoints_parent_dir: null
  checkpoints_name_list: all
  batch_size: 1
  epoch_index: null
  checkpoint_path: null
  test_save_parent_path: null
  checkpoint_name: all
general:
  name: luna_2025-05-23_23:31:44
  wandb: online
  mode: train_and_test
  seed: 0
  enable_progress_bar: true
  local_saved_path: /mlbio_scratch/anagupta/luna/LUNA/exp/train_results
  debug: false
train:
  n_epochs: 1000
  batch_size: 4
  lr: 0.0005
  fast_dev_run: false
  weight_decay: 1.0e-12
model:
  n_layers: 8
  diffusion_noise_schedule: cosine
  diffusion_steps: 1000
  nu:
    p: 2
  hidden_mlp_dims:
    X: 256
    'y': 256
    pos: 64
  hidden_dims:
    dx: 256
    dy: 1
    num_heads: 16
    dim_ffX: 256
    dim_ffy: 256
    dd: 64
    output_features_to_pos_dims: 4
    cell_image_dimensions: 32
distribute:
  gpus_per_node:
  - 1
  - 2
  - 3
  - 4
dataset:
  dataset_name: luna_with_cell_images
  gene_columns_start: 13
  gene_columns_end: 360
  train_data_path: /mlbio_scratch/anagupta/luna/data/train_test_split_1/train_data.csv
  test_data_path: /mlbio_scratch/anagupta/luna/data/train_test_split_1/test_data.csv
  slice_images_path: /mlbio_scratch/anagupta/luna/data/train_test_split_1/slice_images
  train_cell_images_path: /mlbio_scratch/anagupta/luna/data/train_test_split_1/train_cell_images
  test_cell_images_path: /mlbio_scratch/anagupta/luna/data/train_test_split_1/test_cell_images
  validation_data_path: null
  maximum_graph_size:
    train: 1000
    test: 1000
    validation: null
